version: '3.2'

services:
    php:
        volumes:
            - ./composer.json:/var/www/html/composer.json
            - ./composer.lock:/var/www/html/composer.lock
            - jira-reporter:/var/www/html:nocopy       # Replace project_name with the name of your project

volumes:
    jira-reporter:                                     # Replace project_name with the name of your project
        external: true